server:
  host: 127.0.0.1
  port: 8080
endpoints:
  - name: test-oauth-with-different-resource-url
    url: https://config-base-url.example.com  # Base URL (应该被忽略)
    endpoint_type: anthropic
    auth_type: oauth
    enabled: true
    priority: 1
    tags: []
    oauth_config:
      access_token: sk-ant-oat01-test-access-token
      refresh_token: sk-ant-ort01-test-refresh-token
      expires_at: 1755272917673
      resource_url: https://api.anthropic.com  # 实际用于API请求的URL
      token_url: https://console.anthropic.com/v1/oauth/token  # 用于token刷新
      client_id: 9d1c250a-e61b-44d9-88ed-5944d1962f5e
      scopes:
        - user:inference
        - user:profile
      auto_refresh: true
logging:
  level: debug
  log_request_types: all
  log_request_body: full
  log_response_body: full
  log_directory: ./logs
validation:
  strict_anthropic_format: false
  validate_streaming: false
  disconnect_on_invalid: false
tagging:
  pipeline_timeout: 5s
  taggers: []
timeouts:
  proxy:
    tls_handshake: 10s
    response_header: 60s
    idle_connection: 90s
    overall_request: ""
  health_check:
    tls_handshake: 5s
    response_header: 30s
    idle_connection: 60s
    overall_request: 30s
    check_interval: 30s